from pathlib import Path

ROOT = Path(__file__).parent

DATA_DIR = ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
EXPORTS_DIR = DATA_DIR / "exports"
MODELS_DIR = DATA_DIR / "models"

CAPACITY_MW = 560
EFFICIENCY = 0.75
UTILIZATION = 0.75
EFFECTIVE_CAPACITY_MW = CAPACITY_MW * UTILIZATION  # 420 MW

PERIODS_PER_DAY = 48
PERIODS_PER_YEAR = 17520
MAP_CAP = 4500.0  # $/MWh

COLOR_USEP = "#009CEA"
COLOR_DEMAND = "#f0b429"
COLOR_SOLAR = "#2ecc71"
COLOR_SPIKE = "#e74c3c"
COLOR_FORECAST = "#9b59b6"
COLOR_CONFIDENCE = "rgba(0, 156, 234, 0.15)"
